name: Build APK
on:
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3
     with: 
      fetch-depth: 0
      submodules: recursive

   - name: Setup JDK 11
     uses: actions/setup-java@v3
     with:
      java-version: "11"
      distribution: "temurin"

   - name: Build APK
     run: |
      ./gradlew assembleDebug
      mkdir out
      mv app/build/outputs/apk/debug/app-debug.apk out/

   - name: Upload APK to artifact
     uses: actions/upload-artifact@v3
     with:
      name: app-debug
      path: out/app-debug.apk

   - name: Upload APK to release
     uses: svenstaro/upload-release-action@v2
     with:
      file: out/app-debug.apk
      overwrite: true
