name: Build APK
on: [workflow_call, workflow_dispatch]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3
     with: 
      fetch-depth: 0
      submodules: true

   - name: Setup JDK 11
     uses: actions/setup-java@v1
     with:
      java-version: "11"

   - name: Build APK
     run: |
      ./gradlew assembleDebug
      mkdir out
      mv app/build/outputs/apk/debug/app-debug.apk out/

   - name: Upload APK
     uses: actions/upload-artifact@v2
     with:
      name: app-debug.apk
      path: out/app-debug.apk
